spring.application.name=EnterpriseTester

spring.datasource.url=jdbc:mysql://localhost:3306/enterprisetesterdb
spring.datasource.username=root
spring.datasource.password=240507009
# Test passing
testing.enable-time-limit=true
testing.show-countdown=true
testing.multi-answer-mode=NONE
testing.default-questions-count=20
